INSERT INTO ProFootballReference.dbo.TeamLogos (TeamName, LogoURL)
 SELECT * FROM (VALUES
 ('Arizona Cardinals','https://static.www.nfl.com/image/private/f_auto/league/u9fltoslqdsyao8cpm0k')
,('Atlanta Falcons','https://static.www.nfl.com/image/private/f_auto/league/d8m7hzpsbrl6pnqht8op')
,('Baltimore Ravens','https://res.cloudinary.com/nflleague/image/private/f_auto/league/ucsdijmddsqcj1i9tddd')
,('Buffalo Bills','https://res.cloudinary.com/nflleague/image/private/f_auto/league/giphcy6ie9mxbnldntsf')
,('Carolina Panthers','https://static.www.nfl.com/image/private/f_auto/league/ervfzgrqdpnc7lh5gqwq')
,('Chicago Bears','https://static.www.nfl.com/image/private/f_auto/league/ra0poq2ivwyahbaq86d2')
,('Cincinnati Bengals','https://res.cloudinary.com/nflleague/image/private/f_auto/league/okxpteoliyayufypqalq')
,('Cleveland Browns','https://static.www.nfl.com/image/private/f_auto/league/fgbn8acp4opvyxk13dcy')
,('Dallas Cowboys','https://static.www.nfl.com/image/private/f_auto/league/ieid8hoygzdlmzo0tnf6')
,('Denver Broncos','https://res.cloudinary.com/nflleague/image/private/f_auto/league/t0p7m5cjdjy18rnzzqbx')
,('Detroit Lions','https://res.cloudinary.com/nflleague/image/private/f_auto/league/ocvxwnapdvwevupe4tpr')
,('Green Bay Packers','https://res.cloudinary.com/nflleague/image/private/f_auto/league/gppfvr7n8gljgjaqux2x')
,('Houston Texans','https://static.www.nfl.com/image/private/f_auto/league/bpx88i8nw4nnabuq0oob')
,('Indianapolis Colts','https://static.www.nfl.com/image/private/f_auto/league/ketwqeuschqzjsllbid5')
,('Jacksonville Jaguars','https://res.cloudinary.com/nflleague/image/private/f_auto/league/qycbib6ivrm9dqaexryk')
,('Kansas City Chiefs','https://res.cloudinary.com/nflleague/image/private/f_auto/league/ujshjqvmnxce8m4obmvs')
,('Los Angeles Rams','https://static.www.nfl.com/image/private/f_auto/league/ayvwcmluj2ohkdlbiegi')
,('Los Angeles Chargers','https://static.www.nfl.com/image/private/f_auto/league/dhfidtn8jrumakbogeu4')
,('Las Vegas Raiders','https://static.www.nfl.com/image/private/f_auto/league/gzcojbzcyjgubgyb6xf2')
,('Miami Dolphins','https://res.cloudinary.com/nflleague/image/private/f_auto/league/lits6p8ycthy9to70bnt')
,('Minnesota Vikings','https://res.cloudinary.com/nflleague/image/private/f_auto/league/teguylrnqqmfcwxvcmmz')
,('New England Patriots','https://res.cloudinary.com/nflleague/image/private/f_auto/league/moyfxx3dq5pio4aiftnc')
,('New Orleans Saints','https://static.www.nfl.com/image/private/f_auto/league/grhjkahghjkk17v43hdx')
,('New York Giants','https://res.cloudinary.com/nflleague/image/private/f_auto/league/t6mhdmgizi6qhndh8b9p')
,('New York Jets','https://static.www.nfl.com/image/private/f_auto/league/ekijosiae96gektbo4iw')
,('Philadelphia Eagles','https://res.cloudinary.com/nflleague/image/private/f_auto/league/puhrqgj71gobgdkdo6uq')
,('Pittsburgh Steelers','https://res.cloudinary.com/nflleague/image/private/f_auto/league/xujg9t3t4u5nmjgr54wx')
,('Seattle Seahawks','https://res.cloudinary.com/nflleague/image/private/f_auto/league/gcytzwpjdzbpwnwxincg')
,('San Francisco 49ers','https://res.cloudinary.com/nflleague/image/private/f_auto/league/dxibuyxbk0b9ua5ih9hn')
,('Tampa Bay Buccaneers','https://static.www.nfl.com/image/private/f_auto/league/v8uqiualryypwqgvwcih')
,('Tennessee Titans','https://static.www.nfl.com/image/private/f_auto/league/pln44vuzugjgipyidsre')
,('Washington Commanders','https://static.www.nfl.com/image/private/f_auto/league/xymxwrxtyj9fhaemhdyd')) as a (TeamName, LogoURL)
WHERE NOT EXISTS (SELECT 1 FROM TeamLogos tl WHERE a.TeamName = tl.TeamName AND a.LogoURL = tl.LogoURL)