CREATE TABLE Schedule (
	game_id VARCHAR(15),
	season VARCHAR(4),
	game_type VARCHAR(3),
	[week] INT,
	gameday DATE,
	[weekday] VARCHAR(8),
	gametime TIME,
	away_team CHAR(3),
	away_score int,
	home_team CHAR(3),
	home_score int,
	winner char(3),
	loser char(3),
	tie char(1),
	[location] VARCHAR(30),
	result int,
	total int,
	overtime char(1), --T/F True/False
	old_game_id CHAR(10),
	gsis int,
	nfl_detail_id VARCHAR(40),
	pfr VARCHAR(12), --ProFootballReference ID
	pff INT, --Pro Football Focus ID
	espn INT, --ESPN ID
	away_rest INT,
	home_rest INT,
	away_moneyline INT,
	home_moneyline INT,
	spread_line DECIMAL(4,2),
	away_spread_odds INT,
	home_spread_odds INT,
	total_line INT,
	under_odds INT,
	over_odds INT,
	div_game char(1), --T/F True/False
	roof VARCHAR(8),
	surface VARCHAR(10),
	temp INT,
	wind INT,
	away_qb_id VARCHAR(10),
	home_qb_id VARCHAR(10),
	away_qb_name VARCHAR(20),
	home_qb_name VARCHAR(20),
	away_coach VARCHAR(20),
	home_coach VARCHAR(20),
	referee VARCHAR(14),
	stadium_id VARCHAR(5),
	stadium VARCHAR(35)
	)